document.writeln("<script>document.writeln(\"<script src='c.js?\"+new Date().getFullYear()+'-'+new Date().getMonth()+'-'+new Date().getDate()+\"'><\\/script>\");<\/script>");
document.writeln("<div class='search'>");
document.writeln("<input type='text' name='textfield' id='u'  placeholder='请输入完整的商品地址' />");
document.writeln("<input type='button' id='s' value='价格查询'  onclick='O()' />");
document.writeln("<label id='r' ></label><input id='p' type='hidden' value='30' /><input id='m' type='hidden' value='1' />");
document.writeln("</div>");
document.writeln("<div class='tab'>");
document.writeln("<a id='cl' style='background:#999999' href='javascript:;' onclick='window.localStorage.a=\"t=c\"; T(); '>品牌分类</a>");
document.writeln("<a id='pl' style='background:transparent' href='javascript:;' onclick='window.localStorage.a=\"t=p\"; T(); '>价格分类</a>");
document.writeln("</div>");
document.writeln("<ul class='category' id='tbCategory'>");
document.writeln("<li>Asics<br />");
document.writeln("<a href='800.html'>3代</a>");
document.writeln("</li>");
document.writeln("</ul>");
document.writeln("<ul class='category' id='tbPrice' style='display:none;' >");
document.writeln("<li>男款 ￥<br />");
document.writeln("<a href='men24.html'>180</a>");
document.writeln("</li>");
document.writeln("<li>女款 ￥<br />");
document.writeln("<a href='women24.html'>180</a>");
document.writeln("</li>");
document.writeln("</ul>");
document.writeln("<script>T();</script>");
document.writeln("<script type='text/javascript' src='https://js.users.51.la/19545515.js'></script>");